### ISSUE TITLE
Can't install with symfony 2.7

### ISSUE THREAD

**Issue by rbaarsma** [eymengunay/PassbookBundle#8]
Today another bundle in my composer won't install without symfony 2.7, while your bundle is unwilling to install with symfony 2.7. Therefore I can't install or update my application anymore. Is there a specific reason why this bundle is limited to max symfony 2.6? Can you otherwise remove this restriction?

**Comment by eymengunay** [comment]
Thanks @rbaarsma for the heads up. I've updated composer.json and published a new release. You can now use the bundle with Symfony 2.7
